name: CI/ Execute E2E's

on:
  pull_request:
  workflow_dispatch: # For manual testing purposes

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: true

jobs:
  setup-and-execute-tests:
    name: Run E2E Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1/2, 2/2]
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Run Playwright tests
      run: npx playwright test --shard ${{ matrix.shard }}

    - name: Upload blob report to GitHub Actions Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: merged-reports-as-blob 
        path: blob-report 
        retention-days: 30


  merge-reports-and-upload:
    if: always()
    needs: [setup-and-execute-tests]
    runs-on: ubuntu-latest

    outputs:
        timestamp: ${{ steps.timestampid.outputs.timestamp }}

    steps:
    # Unique identifier to be used when we create subdirectories for our github pages with reports (eg of value: 20231028_233147Z)
    - name: Set a timestamp
      id: timestampid
      run: echo "timestamp=$(date --utc +%Y%m%d_%H%M%SZ)" >> "$GITHUB_OUTPUT" 

    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm ci

    # Download the reports uploaded previously to merge them and create one single html report
    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v3
      with:
        name: merged-reports-as-blob
        path: downloaded-merged-reports-as-blob 

    - name: Merge the blobs into one single HTML Report
      run: npx playwright merge-reports --reporter html ./downloaded-merged-reports-as-blob

    - name: Upload merged html report to artifacts for backup history
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report-${{ steps.timestampid.outputs.timestamp }} 
        path: playwright-report 
        retention-days: 30

    - name: Deploy the new files to github pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./playwright-report 
        destination_dir: ${{ steps.timestampid.outputs.timestamp }} 
        keep_files: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
